LANGUAGES = {
    "tr": {
        "app_title": "S2T2S",
        "app_subtitle": "Ses-Metin Dönüşüm ve Özetleme Sistemi",
        "instructions_title": "Talimatlar",
        "instructions": [
            "1. Ses dosyanızı yükleyin (.mp3, .m4a, .wav)",
            "2. **İşlemi Başlat** butonuna tıklayın",
            "3. Transkripsiyon ve özetleme sürecini takip edin",
            "4. Sonuçlar hazır olduğunda inceleyip indirebilirsiniz"
        ],
        "control_panel": "Kontrol Paneli",
        "select_audio": "🎵 Ses dosyası seçin",
        "file_name": "Dosya Adı",
        "size": "Boyut",
        "start_button": "🚀 İşlemi Başlat",
        "stop_button": "🛑 Durdur",
        "recent_processes": "Son İşlemler",
        "no_processes": "Henüz işlem yapılmamış",
        "download_transcription": "Transkripsiyon İndir",
        "download_summary": "Özet İndir",
        "processing": "İşlem devam ediyor...",
        "audio_converting": "🔄 Ses dosyası dönüştürülüyor...",
        "audio_splitting": "✂️ Ses dosyası parçalara bölünüyor...",
        "transcribing": "🎤 Transkripsiyon yapılıyor...",
        "transcribing_segment": "🎤 Transkripsiyon: Segment {}/{}",
        "summarizing": "📝 Metin özetleniyor (bu işlem biraz sürebilir)...",
        "summarizing_model": "🧠 {} modeli ile kapsamlı özet oluşturuluyor...",
        "summary_success": "✅ Özet başarıyla oluşturuldu!",
        "summary_short": "⚠️ Özet oluşturuldu ancak beklenenden kısa",
        "fallback_model": "⚠️ Ana model ile özet oluşturulamadı. Yedek modele geçiliyor...",
        "comprehensive_summary": "✅ Kapsamlı özet tamamlandı!",
        "simple_summary": "⚠️ Basit özet tamamlandı (kapsamlı özet oluşturulamadı)",
        "summary_error": "❌ Özet oluşturma hatası!",
        "saving_results": "💾 Sonuçlar kaydediliyor...",
        "process_completed": "✅ İşlem tamamlandı!",
        "process_completed_message": "Transkripsiyon ve özetleme işlemi başarıyla tamamlandı!",
        "transcription_error": "Transkripsiyon işlemi başarısız oldu. Ses dosyasını kontrol edin veya başka bir dosya deneyin.",
        "process_failed": "İşlem başarısız",
        "process_stopped": "İşlem kullanıcı tarafından durduruldu.",
        "process_error": "İşlem sırasında hata oluştu: {}",
        "summary_tab": "📝 Özet",
        "transcription_tab": "🎤 Transkripsiyon",
        "files_tab": "📂 Dosyalar",
        "summary_header": "Oluşturulan Özet",
        "summary_info": "Aşağıda ses dosyasının özetlenmiş içeriği yer almaktadır.",
        "download_summary_button": "📥 Özeti İndir",
        "summary_downloaded": "Özet başarıyla indirildi!",
        "transcription_header": "Transkripsiyon",
        "transcription_info": "Aşağıda ses dosyasının transkripsiyon metni yer almaktadır.",
        "download_transcription_button": "📥 Transkripsiyonu İndir",
        "transcription_downloaded": "Transkripsiyon başarıyla indirildi!",
        "saved_files_header": "Kaydedilen Dosyalar",
        "transcription_file": "📄 Transkripsiyon Dosyası",
        "summary_file": "📄 Özet Dosyası",
        "files_stored_info": "Dosyalar '{}' dizininde saklanıyor.",
        "select_language": "Dil Seçimi",
        "summary_options": "Özet Seçenekleri",
        "select_summary_mode": "Özet modunu seçin",
        "basic_mode": "Temel Özet",
        "enhanced_mode": "Gelişmiş Özet (Daha uzun sürer)",
        "summary_mode_help": "Gelişmiş özet daha kapsamlı ve detaylı, ancak 2 kat daha uzun sürer.",
        "basic_summarizing": "🔄 Temel özet oluşturuluyor...",
        "enhanced_summarizing": "🧠 Gelişmiş özet oluşturuluyor (bu işlem daha uzun sürebilir)..."

    },
    "en": {
        "app_title": "S2T2S",
        "app_subtitle": "Sound-Text Conversion and Summary System",
        "instructions_title": "Instructions",
        "instructions": [
            "1. Upload your audio file (.mp3, .m4a, .wav)",
            "2. Click the **Start Process** button",
            "3. Monitor the transcription and summarization process",
            "4. When results are ready, you can review and download them"
        ],
        "control_panel": "Control Panel",
        "select_audio": "🎵 Select audio file",
        "file_name": "File Name",
        "size": "Size",
        "start_button": "🚀 Start Process",
        "stop_button": "🛑 Stop",
        "recent_processes": "Recent Processes",
        "no_processes": "No processes yet",
        "download_transcription": "Download Transcription",
        "download_summary": "Download Summary",
        "processing": "Processing...",
        "audio_converting": "🔄 Converting audio file...",
        "audio_splitting": "✂️ Splitting audio file into segments...",
        "transcribing": "🎤 Transcribing...",
        "transcribing_segment": "🎤 Transcription: Processing segment {}/{}",
        "summarizing": "📝 Summarizing text (this may take a while)...",
        "summarizing_model": "🧠 Creating comprehensive summary with {} model...",
        "summary_success": "✅ Summary successfully created!",
        "summary_short": "⚠️ Summary created but shorter than expected",
        "fallback_model": "⚠️ Could not create summary with primary model. Switching to fallback model...",
        "comprehensive_summary": "✅ Comprehensive summary completed!",
        "simple_summary": "⚠️ Simple summary completed (could not create comprehensive summary)",
        "summary_error": "❌ Summary creation error!",
        "saving_results": "💾 Saving results...",
        "process_completed": "✅ Process completed!",
        "process_completed_message": "Transcription and summarization process successfully completed!",
        "transcription_error": "Transcription process failed. Check your audio file or try another file.",
        "process_failed": "Process failed",
        "process_stopped": "Process stopped by user.",
        "process_error": "Error during process: {}",
        "summary_tab": "📝 Summary",
        "transcription_tab": "🎤 Transcription",
        "files_tab": "📂 Files",
        "summary_header": "Generated Summary",
        "summary_info": "Below is the summarized content of the audio file.",
        "download_summary_button": "📥 Download Summary",
        "summary_downloaded": "Summary downloaded successfully!",
        "transcription_header": "Transcription",
        "transcription_info": "Below is the transcription text of the audio file.",
        "download_transcription_button": "📥 Download Transcription",
        "transcription_downloaded": "Transcription downloaded successfully!",
        "saved_files_header": "Saved Files",
        "transcription_file": "📄 Transcription File",
        "summary_file": "📄 Summary File",
        "files_stored_info": "Files are stored in the '{}' directory.",
        "select_language": "Language Selection",
        "summary_options": "Summary Options",
        "select_summary_mode": "Select summary mode",
        "basic_mode": "Basic Summary",
        "enhanced_mode": "Enhanced Summary (Takes longer)",
        "summary_mode_help": "Enhanced summary is more comprehensive and detailed, but takes twice as long.",
        "basic_summarizing": "🔄 Creating basic summary...",
        "enhanced_summarizing": "🧠 Creating enhanced summary (this may take longer)..."
    }
}

def get_text(lang, key):
    """Belirtilen dil ve anahtar için metni döndürür."""
    if lang not in LANGUAGES:
        lang = "tr"  
    
    return LANGUAGES[lang].get(key, f"Missing text: {key}")